name: phylofoundry
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas
  - scikit-bio
  - numpy
  - scikit-learn
  - umap-learn
  - hmmer
  - mafft
  - clipkit
  - iqtree  # Installs iqtree v2.x.
  - pal2nal # For codon alignments
  - hyphy   # For selection analysis
  - pytorch
  - transformers
  - pygenomeviz
  - biopython
  - matplotlib
  - diamond
  - mmseqs2
  - pip
  - pip:
    - fair-esm
    - biopython
    - .  # Install the current package in editable mode
