name: phylofoundry
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas
  - scikit-bio
  - numpy
  - scikit-learn
  - umap-learn
  - hmmer
  - mafft
  - clipkit
  - iqtree 
  - pal2nal
  - pygenomeviz
  - biopython
  - matplotlib
  - diamond
  - mmseqs2
  - umap-learn
  - iqtree
  - hyphy
  - pip
  - pip:
    - fair-esm
    - pygenomeviz
    - biopython
    - transformers
    - torch
    - .  # Install the current package in editable mode
